let currentTask=null;let selected=null;let hintsLeft=3;let progress={};let levelsCount=3;const tasks={'Паролі':[{q:"Який пароль найбезпечніший?",type:"single",o:["123456","password","Tr0ub4dor&3","admin"],c:2,hint:"Містить цифри, символи, великі+малі літери"},{q:"Виберіть ВСІ ознаки сильного пароля",type:"multi",o:["8+ символів","Тільки цифри","Великі+малі літери","Символи !@#"],c:[0,2,3],hint:"Все крім 'тільки цифри'"},{q:"Яка мінімальна довжина пароля?",type:"input",answer:"12",hint:"Рекомендовано 12+ символів"},{q:"Чи можна 'password'?",type:"single",o:["Так","Ні, найслабший!"],c:1,hint:"№1 у списку злому"},{q:"Рекомендовано:",type:"multi",o:["Унікальний","В браузері","Менеджер паролів","Міняти щомісяця?"],c:[0,2],hint:"Браузер небезпечний"},{q:"Що таке менеджер паролів?",type:"single",o:["Програма для зберігання паролів","Антивірус","Браузер"],c:0,hint:"Зберігає і генерує паролі"},{q:"Які дії підвищують безпеку пароля?",type:"multi",o:["Використовувати різні паролі","Писати на папері","Використовувати двофакторну автентифікацію","Ділитися з друзями"],c:[0,2],hint:"Тільки безпечні дії"}],'Соцмережі':[{q:"Що НЕ публікувати?",type:"multi",o:["Фото їжі","Адреса дому","Телефон","Відпустка зараз"],c:[1,2,3],hint:"Особисті дані = небезпека"},{q:"Запити від незнайомців?",type:"single",o:["Приймати","Відмовити"],c:1,hint:"99% - шахраї"},{q:"Що робити при підозрілих повідомленнях?",type:"single",o:["Ігнорувати/Видаляти","Відповісти","Поділитися з друзями"],c:0,hint:"Не взаємодійте"},{q:"Які налаштування приватності важливі?",type:"multi",o:["Закрити профіль","Ділитися всім","Обмежити друзі","Публікувати пости тільки для друзів"],c:[0,2,3],hint:"Все, що обмежує доступ"}],'Електронна пошта':[{q:"Лист 'Банк - введіть пароль'?",type:"single",o:["Ввести","Видалити","Відповісти"],c:1,hint:"Банки НЕ просять пароль"},{q:"Підозріле вкладення?",type:"single",o:["Відкрити","Видалити"],c:1,hint:"Вірус 100%"},{q:"Фішинговий лист можна розпізнати по:",type:"multi",o:["Невідомий відправник","Помилки в тексті","Запит пароля","Вкладення без причини"],c:[0,2,3],hint:"Звертайте увагу на підозрілі деталі"}],'Фішинг':[{q:"Ознаки фішингу:",type:"multi",o:["Невідомий","Терміново!","Підозріле посилання","Ідеальна граматика?"],c:[0,1,2],hint:"Все крім граматики"},{q:"Що робити при фішинговому посиланню?",type:"single",o:["Відкрити","Ігнорувати/Видалити"],c:1,hint:"Не клікайте на підозрілі посилання"},{q:"Як підвищити захист від фішингу?",type:"multi",o:["Встановити антивірус","Клікати по всім посиланням","Перевіряти URL","Використовувати двофакторну автентифікацію"],c:[0,2,3],hint:"Все, що додає безпеку"}]};function loadProgress(){const saved=localStorage.getItem('cyberProgress');progress=saved?JSON.parse(saved):{'Паролі':0,'Соцмережі':0,'Електронна пошта':0,'Фішинг':0};updateProgressUI();updateLevels()}
function saveProgress(){localStorage.setItem('cyberProgress',JSON.stringify(progress))}
function updateProgressUI(){['Паролі','Соцмережі','Електронна пошта','Фішинг'].forEach(theme=>{const perc=progress[theme]||0;const progEl=document.getElementById(`prog-${theme.toLowerCase().replace(' ', '-')}`);const fillEl=document.getElementById(`fill-${theme.toLowerCase().replace(' ', '-')}`);if(progEl)progEl.textContent=perc+'%';if(fillEl)fillEl.style.width=perc+'%'})}
function goTo(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='progress')renderProgressBars()}
function startTheme(theme){currentTask={theme,index:0,correct:0,total:tasks[theme].length};selected=null;hintsLeft=3;document.getElementById('theme-title').textContent=`Тема: ${theme}`;document.getElementById('level-title').textContent=`Рівень ${currentTask.index + 1}`;document.getElementById('hint-count').textContent=hintsLeft;loadTask();goTo('game')}
function loadTask(){const task=tasks[currentTask.theme][currentTask.index];const input=document.getElementById('text-input');const optionsDiv=document.getElementById('options');document.getElementById('task-text').textContent=`📝 ${task.q}`;input.style.display=task.type==='input'?'block':'none';input.value='';optionsDiv.innerHTML='';if(task.type!=='input'){task.o.forEach((opt,i)=>{const div=document.createElement('div');div.className='option';div.textContent=opt;div.onclick=()=>selectOption(i,task.type);optionsDiv.appendChild(div)})}
selected=task.type==='multi'?[]:null;updateOptions()}
function selectOption(i,type){if(type==='multi'){selected.includes(i)?selected=selected.filter(x=>x!==i):selected.push(i)}else{selected=i}
updateOptions()}
function updateOptions(){document.querySelectorAll('.option').forEach((opt,i)=>{opt.classList.remove('selected');if(Array.isArray(selected)&&selected.includes(i))opt.classList.add('selected');else if(selected===i)opt.classList.add('selected')})}
function checkAnswer(){const input=document.getElementById('text-input');const task=tasks[currentTask.theme][currentTask.index];const errorMsg=document.getElementById('error-msg');errorMsg.textContent='';let isCorrect=!1;if(task.type==='input'){if(!input.value.trim()){errorMsg.textContent='Введіть відповідь!';return}
selected=input.value.trim();isCorrect=selected.toLowerCase()===task.answer.toLowerCase()}else{if(selected===null||(Array.isArray(selected)&&selected.length===0)){errorMsg.textContent='Виберіть відповідь!';return}
if(task.type==='multi')isCorrect=JSON.stringify(selected.sort())===JSON.stringify(task.c.sort());else isCorrect=selected===task.c}
document.getElementById('points-earned').textContent=isCorrect?'50 балів':'0 балів';document.getElementById('result-icon').textContent=isCorrect?'✅':'❌';document.getElementById('result-text').textContent=isCorrect?'Правильно!':'Спробуйте ще!';if(!isCorrect){errorMsg.textContent='❌ Неправильно, спробуйте ще раз!';setTimeout(()=>{selected=task.type==='multi'?[]:null;if(task.type==='input')input.value='';updateOptions()},1000);return}
currentTask.correct++;showResultScreen()}
function showResultScreen(){document.querySelectorAll('.option').forEach(opt=>opt.classList.remove('correct','wrong'));setTimeout(()=>{goTo('result-screen');document.getElementById('next-level-btn').onclick=nextTask},300)}
function nextTask(){currentTask.index++;if(currentTask.index>=currentTask.total){const accuracy=Math.round((currentTask.correct/currentTask.total)*100);progress[currentTask.theme]=accuracy;saveProgress();updateProgressUI();updateLevels();alert(`Тема "${currentTask.theme}" завершена!\nТочність: ${accuracy}%`);goTo('main-menu')}else{loadTask();document.getElementById('theme-title').textContent=`Тема: ${currentTask.theme}`;document.getElementById('level-title').textContent=`Рівень ${currentTask.index + 1}`;goTo('game')}}
function useHint(){if(hintsLeft<=0)return alert('😔 Підказки закінчились!');const task=tasks[currentTask.theme][currentTask.index];hintsLeft--;document.getElementById('hint-count').textContent=hintsLeft;alert(`💡 Підказка: ${task.hint}\nЗалишилось: ${hintsLeft}`)}
function renderProgressBars(){const container=document.getElementById('progress-bars');container.innerHTML='';['Паролі','Соцмережі','Електронна пошта','Фішинг'].forEach(theme=>{const perc=progress[theme]||0;const div=document.createElement('div');div.className='progress-bar';div.innerHTML=`
      <div class="label">${theme} <span id="prog-${theme.toLowerCase().replace(' ','-')}">${perc}%</span></div>
      <div class="bar"><div class="fill" id="fill-${theme.toLowerCase().replace(' ','-')}" style="width:${perc}%"></div></div>
    `;container.appendChild(div)})}
function updateLevels(){const container=document.getElementById('levels-list');container.innerHTML='';Object.keys(tasks).forEach(theme=>{for(let i=0;i<levelsCount;i++){const levelDiv=document.createElement('div');levelDiv.className='level-item';let status='locked';let statusText='Заблоковано';if(progress[theme]===100){status=i===0?'done':'locked';statusText=i===0?'Пройдено':'Заблоковано'}
if(i===0){status='active';statusText='Початок'}
if(progress[theme]&&i<progress[theme]/100*levelsCount){status='done';statusText='Пройдено'}
levelDiv.innerHTML=`${theme} - Рівень ${i + 1}<span class="status ${status}">${statusText}</span>`;levelDiv.onclick=()=>{if(status!=='locked')startTheme(theme)};container.appendChild(levelDiv)}})}
loadProgress()